services:
  stepanka:
    build: ./server
    volumes:
      - stepanka_db:/app/data
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      caddy: "http://stepanka.vitakriz.cz, http://kata.vitakriz.cz"
      caddy.reverse_proxy: "{{upstreams 3000}}"

volumes:
  stepanka_db:

networks:
  proxy:
    external: true
